/*
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeDetails.proto

package com.benzassignment.file.service.protobuf;

public final class EmployeeDetailsOuterClass {
  private EmployeeDetailsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EmployeeDetails)
      com.google.protobuf.MessageOrBuilder {

    */
/**
     * <code>required string name = 1;</code>
     *//*

    boolean hasName();
    */
/**
     * <code>required string name = 1;</code>
     *//*

    java.lang.String getName();
    */
/**
     * <code>required string name = 1;</code>
     *//*

    com.google.protobuf.ByteString
        getNameBytes();

    */
/**
     * <code>required string dob = 2;</code>
     *//*

    boolean hasDob();
    */
/**
     * <code>required string dob = 2;</code>
     *//*

    java.lang.String getDob();
    */
/**
     * <code>required string dob = 2;</code>
     *//*

    com.google.protobuf.ByteString
        getDobBytes();

    */
/**
     * <code>required string salary = 3;</code>
     *//*

    boolean hasSalary();
    */
/**
     * <code>required string salary = 3;</code>
     *//*

    java.lang.String getSalary();
    */
/**
     * <code>required string salary = 3;</code>
     *//*

    com.google.protobuf.ByteString
        getSalaryBytes();

    */
/**
     * <code>required int64 age = 4;</code>
     *//*

    boolean hasAge();
    */
/**
     * <code>required int64 age = 4;</code>
     *//*

    long getAge();

    */
/**
     * <code>required string fileType = 5;</code>
     *//*

    boolean hasFileType();
    */
/**
     * <code>required string fileType = 5;</code>
     *//*

    java.lang.String getFileType();
    */
/**
     * <code>required string fileType = 5;</code>
     *//*

    com.google.protobuf.ByteString
        getFileTypeBytes();

    */
/**
     * <code>required string operation = 6;</code>
     *//*

    boolean hasOperation();
    */
/**
     * <code>required string operation = 6;</code>
     *//*

    java.lang.String getOperation();
    */
/**
     * <code>required string operation = 6;</code>
     *//*

    com.google.protobuf.ByteString
        getOperationBytes();
  }
  */
/**
   * Protobuf type {@code EmployeeDetails}
   *//*

  public  static final class EmployeeDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EmployeeDetails)
      EmployeeDetailsOrBuilder {
    // Use EmployeeDetails.newBuilder() to construct.
    private EmployeeDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmployeeDetails() {
      name_ = "";
      dob_ = "";
      salary_ = "";
      age_ = 0L;
      fileType_ = "";
      operation_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmployeeDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              dob_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              salary_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              age_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              fileType_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              operation_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.internal_static_EmployeeDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.internal_static_EmployeeDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails.class, com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    */
/**
     * <code>required string name = 1;</code>
     *//*

    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    */
/**
     * <code>required string name = 1;</code>
     *//*

    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string name = 1;</code>
     *//*

    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOB_FIELD_NUMBER = 2;
    private volatile java.lang.Object dob_;
    */
/**
     * <code>required string dob = 2;</code>
     *//*

    public boolean hasDob() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    */
/**
     * <code>required string dob = 2;</code>
     *//*

    public java.lang.String getDob() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dob_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string dob = 2;</code>
     *//*

    public com.google.protobuf.ByteString
        getDobBytes() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALARY_FIELD_NUMBER = 3;
    private volatile java.lang.Object salary_;
    */
/**
     * <code>required string salary = 3;</code>
     *//*

    public boolean hasSalary() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    */
/**
     * <code>required string salary = 3;</code>
     *//*

    public java.lang.String getSalary() {
      java.lang.Object ref = salary_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          salary_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string salary = 3;</code>
     *//*

    public com.google.protobuf.ByteString
        getSalaryBytes() {
      java.lang.Object ref = salary_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private long age_;
    */
/**
     * <code>required int64 age = 4;</code>
     *//*

    public boolean hasAge() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    */
/**
     * <code>required int64 age = 4;</code>
     *//*

    public long getAge() {
      return age_;
    }

    public static final int FILETYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object fileType_;
    */
/**
     * <code>required string fileType = 5;</code>
     *//*

    public boolean hasFileType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    */
/**
     * <code>required string fileType = 5;</code>
     *//*

    public java.lang.String getFileType() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileType_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string fileType = 5;</code>
     *//*

    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 6;
    private volatile java.lang.Object operation_;
    */
/**
     * <code>required string operation = 6;</code>
     *//*

    public boolean hasOperation() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    */
/**
     * <code>required string operation = 6;</code>
     *//*

    public java.lang.String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operation_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string operation = 6;</code>
     *//*

    public com.google.protobuf.ByteString
        getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDob()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSalary()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dob_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, salary_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, age_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, operation_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dob_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, salary_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, age_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, operation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails)) {
        return super.equals(obj);
      }
      com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails other = (com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasDob() == other.hasDob());
      if (hasDob()) {
        result = result && getDob()
            .equals(other.getDob());
      }
      result = result && (hasSalary() == other.hasSalary());
      if (hasSalary()) {
        result = result && getSalary()
            .equals(other.getSalary());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && (hasFileType() == other.hasFileType());
      if (hasFileType()) {
        result = result && getFileType()
            .equals(other.getFileType());
      }
      result = result && (hasOperation() == other.hasOperation());
      if (hasOperation()) {
        result = result && getOperation()
            .equals(other.getOperation());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasDob()) {
        hash = (37 * hash) + DOB_FIELD_NUMBER;
        hash = (53 * hash) + getDob().hashCode();
      }
      if (hasSalary()) {
        hash = (37 * hash) + SALARY_FIELD_NUMBER;
        hash = (53 * hash) + getSalary().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAge());
      }
      if (hasFileType()) {
        hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getFileType().hashCode();
      }
      if (hasOperation()) {
        hash = (37 * hash) + OPERATION_FIELD_NUMBER;
        hash = (53 * hash) + getOperation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    */
/**
     * Protobuf type {@code EmployeeDetails}
     *//*

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EmployeeDetails)
        com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.internal_static_EmployeeDetails_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.internal_static_EmployeeDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails.class, com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails.Builder.class);
      }

      // Construct using com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dob_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        salary_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        fileType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        operation_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.internal_static_EmployeeDetails_descriptor;
      }

      public com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails getDefaultInstanceForType() {
        return com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails.getDefaultInstance();
      }

      public com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails build() {
        com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails buildPartial() {
        com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails result = new com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dob_ = dob_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.salary_ = salary_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fileType_ = fileType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.operation_ = operation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails) {
          return mergeFrom((com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails other) {
        if (other == com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDob()) {
          bitField0_ |= 0x00000002;
          dob_ = other.dob_;
          onChanged();
        }
        if (other.hasSalary()) {
          bitField0_ |= 0x00000004;
          salary_ = other.salary_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasFileType()) {
          bitField0_ |= 0x00000010;
          fileType_ = other.fileType_;
          onChanged();
        }
        if (other.hasOperation()) {
          bitField0_ |= 0x00000020;
          operation_ = other.operation_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasDob()) {
          return false;
        }
        if (!hasSalary()) {
          return false;
        }
        if (!hasAge()) {
          return false;
        }
        if (!hasFileType()) {
          return false;
        }
        if (!hasOperation()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      */
/**
       * <code>required string name = 1;</code>
       *//*

      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      */
/**
       * <code>required string name = 1;</code>
       *//*

      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      */
/**
       * <code>required string name = 1;</code>
       *//*

      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string name = 1;</code>
       *//*

      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string name = 1;</code>
       *//*

      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string name = 1;</code>
       *//*

      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dob_ = "";
      */
/**
       * <code>required string dob = 2;</code>
       *//*

      public boolean hasDob() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      */
/**
       * <code>required string dob = 2;</code>
       *//*

      public java.lang.String getDob() {
        java.lang.Object ref = dob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dob_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      */
/**
       * <code>required string dob = 2;</code>
       *//*

      public com.google.protobuf.ByteString
          getDobBytes() {
        java.lang.Object ref = dob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string dob = 2;</code>
       *//*

      public Builder setDob(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dob_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string dob = 2;</code>
       *//*

      public Builder clearDob() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dob_ = getDefaultInstance().getDob();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string dob = 2;</code>
       *//*

      public Builder setDobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dob_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object salary_ = "";
      */
/**
       * <code>required string salary = 3;</code>
       *//*

      public boolean hasSalary() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      */
/**
       * <code>required string salary = 3;</code>
       *//*

      public java.lang.String getSalary() {
        java.lang.Object ref = salary_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            salary_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      */
/**
       * <code>required string salary = 3;</code>
       *//*

      public com.google.protobuf.ByteString
          getSalaryBytes() {
        java.lang.Object ref = salary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          salary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string salary = 3;</code>
       *//*

      public Builder setSalary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        salary_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string salary = 3;</code>
       *//*

      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000004);
        salary_ = getDefaultInstance().getSalary();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string salary = 3;</code>
       *//*

      public Builder setSalaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        salary_ = value;
        onChanged();
        return this;
      }

      private long age_ ;
      */
/**
       * <code>required int64 age = 4;</code>
       *//*

      public boolean hasAge() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      */
/**
       * <code>required int64 age = 4;</code>
       *//*

      public long getAge() {
        return age_;
      }
      */
/**
       * <code>required int64 age = 4;</code>
       *//*

      public Builder setAge(long value) {
        bitField0_ |= 0x00000008;
        age_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required int64 age = 4;</code>
       *//*

      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000008);
        age_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fileType_ = "";
      */
/**
       * <code>required string fileType = 5;</code>
       *//*

      public boolean hasFileType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      */
/**
       * <code>required string fileType = 5;</code>
       *//*

      public java.lang.String getFileType() {
        java.lang.Object ref = fileType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      */
/**
       * <code>required string fileType = 5;</code>
       *//*

      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        java.lang.Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string fileType = 5;</code>
       *//*

      public Builder setFileType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileType_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string fileType = 5;</code>
       *//*

      public Builder clearFileType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string fileType = 5;</code>
       *//*

      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object operation_ = "";
      */
/**
       * <code>required string operation = 6;</code>
       *//*

      public boolean hasOperation() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      */
/**
       * <code>required string operation = 6;</code>
       *//*

      public java.lang.String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            operation_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      */
/**
       * <code>required string operation = 6;</code>
       *//*

      public com.google.protobuf.ByteString
          getOperationBytes() {
        java.lang.Object ref = operation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string operation = 6;</code>
       *//*

      public Builder setOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        operation_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string operation = 6;</code>
       *//*

      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000020);
        operation_ = getDefaultInstance().getOperation();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string operation = 6;</code>
       *//*

      public Builder setOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        operation_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EmployeeDetails)
    }

    // @@protoc_insertion_point(class_scope:EmployeeDetails)
    private static final com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails();
    }

    public static com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EmployeeDetails>
        PARSER = new com.google.protobuf.AbstractParser<EmployeeDetails>() {
      public EmployeeDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EmployeeDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmployeeDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmployeeDetails> getParserForType() {
      return PARSER;
    }

    public com.benzassignment.file.service.protobuf.EmployeeDetailsOuterClass.EmployeeDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EmployeeDetails.proto\"n\n\017EmployeeDetai" +
      "ls\022\014\n\004name\030\001 \002(\t\022\013\n\003dob\030\002 \002(\t\022\016\n\006salary\030" +
      "\003 \002(\t\022\013\n\003age\030\004 \002(\003\022\020\n\010fileType\030\005 \002(\t\022\021\n\t" +
      "operation\030\006 \002(\tB*\n(com.benzassignment.fi" +
      "le.service.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EmployeeDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmployeeDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeDetails_descriptor,
        new java.lang.String[] { "Name", "Dob", "Salary", "Age", "FileType", "Operation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
*/
